In [12]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [13]:
# Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering
import scipy.cluster.hierarchy as sch
plt.style.use('fivethirtyeight')

In [14]:
df = pd.read_csv('/content/drive/MyDrive/PTDataScience/PandasForDataManipulation/breast_cancer.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [15]:
X = df.iloc[:, 3:31].values  #Note: Exclude Last column with all NaN values.
y = df.iloc[:, 2].values

In [16]:
#Encoding Categorical Data
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

y = labelencoder.fit_transform(y)

In [17]:
y

array([370, 426, 406,  98, 418, 159, 376, 233, 192, 160, 324, 322, 394,
       323, 234, 273, 280, 328, 410, 222, 196,  28, 310, 436, 341, 351,
       274, 381, 308, 362, 382, 125, 347, 398, 328, 343, 259, 194, 295,
       217, 213,  73, 391, 206, 201, 383,   4, 201, 137, 218, 122, 227,
       131, 375, 301, 106, 397, 282, 195,   9,  49,   8, 259,  19, 170,
       285,  27,  91,  17, 176, 388,  14, 353, 239, 151, 326, 221, 373,
       415, 181, 100, 208, 451, 392, 134, 379, 270, 390, 154, 279, 278,
       311, 205, 214, 299, 417, 142,  41, 109, 266, 225,   0, 142,  43,
        58, 197, 113, 154, 443,  94,  40, 167, 260,  59,  11, 130,  15,
       289, 322, 369,  97, 384, 449, 271, 209, 242, 225, 389, 301, 408,
       143, 312, 330, 319, 378, 175, 119,  99, 292,  88,  37, 327,  99,
       185,  65, 129, 123, 292, 267, 235, 192,   5,  36,  81, 199, 148,
       364, 345, 138,  70, 121, 396, 404, 153, 446, 294,  66, 344, 360,
       294, 152, 212, 312,  78,  63,  10,  44, 338, 193, 178, 45

In [18]:
#Splitting into Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)


In [19]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [20]:

# define the keras model
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))


In [21]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [22]:
# fit the keras model on the dataset
#model.fit(X, y, epochs=150, batch_size=10)

Ten

In [23]:
import tensorflow as tf

In [24]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [25]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [26]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.07308622, -0.15532127,  0.11821122, -0.07689913,  0.11125173,
        -0.08314126,  0.19864693, -1.3513356 ,  0.67411345, -0.23767044]],
      dtype=float32)

In [27]:
tf.nn.softmax(predictions).numpy()

array([[0.10495093, 0.08351994, 0.10979532, 0.09033343, 0.10903385,
        0.08977132, 0.1189917 , 0.02525619, 0.19142962, 0.07691772]],
      dtype=float32)

In [28]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [29]:
loss_fn(y_train[:1], predictions).numpy()

2.4104898

In [30]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [31]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4894 - accuracy: 0.8585
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1510 - accuracy: 0.9550
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1094 - accuracy: 0.9673
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0882 - accuracy: 0.9724
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0791 - accuracy: 0.9752


In [32]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0775 - accuracy: 0.9767


[0.07746010273694992, 0.9767000079154968]

In [33]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [34]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.3517452e-09, 5.3831639e-10, 1.9381729e-07, 2.0128666e-05,
        7.2944336e-13, 2.8443390e-07, 4.2520411e-16, 9.9997365e-01,
        1.4471640e-07, 5.5777605e-06],
       [2.3176641e-07, 2.6455596e-03, 9.9714547e-01, 1.6410918e-04,
        2.6492588e-15, 1.0934681e-05, 1.6405931e-09, 7.2205618e-12,
        3.3618195e-05, 3.8590099e-12],
       [8.3696975e-08, 9.9947506e-01, 8.6080458e-05, 6.4978954e-06,
        5.3772306e-05, 2.7584861e-06, 1.5189113e-06, 2.8791180e-04,
        8.4511048e-05, 1.8985050e-06],
       [9.9897230e-01, 7.8885972e-07, 4.4507949e-04, 2.7924066e-06,
        9.8222949e-07, 3.9414846e-04, 2.4422197e-05, 1.9342664e-05,
        1.8138921e-06, 1.3835906e-04],
       [3.1962982e-06, 2.3110214e-08, 2.4710587e-05, 4.0568608e-07,
        9.9452329e-01, 2.3863377e-06, 1.9121094e-06, 3.1316031e-05,
        7.9641213e-06, 5.4046977e-03]], dtype=float32)>

In [35]:
# evaluate the keras model
accuracy = model.evaluate(x_test, y_test)
print(accuracy*100)

313/313 [==============================] - 0s 1ms/step - loss: 0.0775 - accuracy: 0.9767
[0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.07746010273694992, 0.9767000079154968, 0.077460

In [36]:
accuracy = model.evaluate(x_test, y_test, verbose=0)
accuracy*100000

[0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010273694992,
 0.9767000079154968,
 0.07746010